Device configured: cuda:0
True
Starting training loop...
Traceback (most recent call last):
  File "run.py", line 84, in <module>
    train(ncf, datasets, hyperparameters)
  File "D:\University\Edinburgh\Dissertation\MM_RecSys_Amazon\training.py", line 60, in train
    for epoch in tqdm(range(max_epochs)):
TypeError: 'module' object is not callable